# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-01-21 14:12
from __future__ import unicode_literals

import audit_history.fields
import audit_history.mixins
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('position', models.IntegerField(default=1)),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('history', audit_history.fields.AuditHistoryField(default=list)),
            ],
            bases=(models.Model, audit_history.mixins.AuditHistoryMixin),
        ),
    ]
